exports.editorGroup = function(palette) {
    return {
        'editorGroup.border': palette.base1,
        // 'editorGroup.dropBackground': '',
        // 'editorGroupHeader.noTabsBackground': '',
        'editorGroupHeader.tabsBackground': palette.base1,
        'editorGroupHeader.tabsBorder': palette.bg,
        'editorGroupHeader.border': palette.bg,
        'editorGroup.emptyBackground': palette.bg,
        'editorGroup.focusedEmptyBorder': palette.bg,
        // 'editorGroup.dropIntoPromptForeground': '',
        // 'editorGroup.dropIntoPromptBackground': '',
        // 'editorGroup.dropIntoPromptBorder': '',

        'tab.activeBackground': palette.bg,
        // 'tab.unfocusedActiveBackground': '',
        'tab.activeForeground': palette.fg,
        'tab.border': palette.base1,
        'tab.activeBorder': palette.bg,
        // 'tab.unfocusedActiveBorder': '',
        'tab.activeBorderTop': palette.bg,
        // 'tab.unfocusedActiveBorderTop': '',
        // 'tab.lastPinnedBorder': '',
        'tab.inactiveBackground': palette.base1,
        // 'tab.unfocusedInactiveBackground': '',
        'tab.inactiveForeground': palette.fg,
        // 'tab.unfocusedActiveForeground': '',
        // 'tab.unfocusedInactiveForeground': '',
        'tab.hoverBackground': palette.base4,
        // 'tab.unfocusedHoverBackground': '',
        'tab.hoverForeground': palette.fg,
        // 'tab.unfocusedHoverForeground': '',
        'tab.hoverBorder': palette.base1,
        // 'tab.unfocusedHoverBorder': '',
        // 'tab.activeModifiedBorder': '',
        // 'tab.inactiveModifiedBorder': '',
        // 'tab.unfocusedActiveModifiedBorder': '',
        // 'tab.unfocusedInactiveModifiedBorder': '',

        'editorPane.background': palette.bg,
        // 'sideBySideEditor.horizontalBorder': '',
        // 'sideBySideEditor.verticalBorder': '',
    }
}