const { lightness, alpha } = require('../base/util');

exports.editor = function (palette) {
    return {
        'editor.background': palette.bg,
        'editor.foreground': palette.fg,
        'editorLineNumber.foreground': lightness(palette.bg, 30),
        'editorLineNumber.activeForeground': palette.fgBright,
        'editorCursor.background': palette.bg,
        'editorCursor.foreground': lightness(palette.bg, 48),
        'editor.selectionBackground': lightness(palette.bg, 8),
        'editor.inactiveSelectionBackground': lightness(palette.bg, 8),
        'editor.selectionHighlightBackground': '#0000',
        // 'editor.selectionHighlightBorder': '',
        'editor.wordHighlightBackground': '#0000',
        // 'editor.wordHighlightBorder': lightness(palette.bg, 4),
        'editor.wordHighlightStrongBackground': '#0000',
        // 'editor.wordHighlightStrongBorder': lightness(palette.bg, 8),
        'editor.findMatchBackground': lightness(palette.bg, 16),
        'editor.findMatchHighlightBackground': lightness(palette.bg, 4),
        'editor.findRangeHighlightBackground': lightness(palette.bg, 4),
        // 'editor.findMatchBorder': '',
        // 'editor.findMatchHighlightBorder': '',
        // 'editor.findRangeHighlightBorder': '',

        // 'searchEditor.findMatchBackground': '',
        // 'searchEditor.findMatchBorder': '',
        // 'searchEditor.textInputBorder': '',
        'editor.hoverHighlightBackground': lightness(palette.bg, 4),
        'editor.lineHighlightBackground': lightness(palette.bg, 2),
        'editor.lineHighlightBorder': lightness(palette.bg, 2),
        // 'editorUnicodeHighlight.border': '',
        // 'editorUnicodeHighlight.background': '',
        'editorLink.activeForeground': lightness(palette.fg, 4),
        // 'editor.rangeHighlightBackground': '',
        // 'editor.rangeHighlightBorder': '',
        // 'editor.symbolHighlightBackground': '',
        // 'editor.symbolHighlightBorder': '',
        'editorWhitespace.foreground': lightness(palette.bg, 6),
        'editorIndentGuide.background': palette.base4,
        'editorIndentGuide.activeBackground': lightness(palette.bg, 8),
        'editorInlayHint.background': palette.bg,
        'editorInlayHint.foreground': palette.fgMuted,
        // 'editorInlayHint.typeForeground': '',
        // 'editorInlayHint.typeBackground': '',
        // 'editorInlayHint.parameterForeground': '',
        // 'editorInlayHint.parameterBackground': '',
        'editorRuler.foreground': palette.base4,
        'editor.linkedEditingBackground': palette.base4,
        'editorCodeLens.foreground': lightness(palette.bg, 16),
        'editorLightBulb.foreground': palette.yellow,
        'editorLightBulbAutoFix.foreground': palette.yellow,
        'editorBracketMatch.background': lightness(palette.bg, 8),
        'editorBracketMatch.border': lightness(palette.bg, 8),
        'editorBracketHighlight.foreground1': palette.fg,
        'editorBracketHighlight.foreground2': palette.fg,
        'editorBracketHighlight.foreground3': palette.fg,
        'editorBracketHighlight.foreground4': palette.fg,
        'editorBracketHighlight.foreground5': palette.fg,
        'editorBracketHighlight.foreground6': palette.fg,
        'editorBracketHighlight.unexpectedBracket.foreground': palette.red,
        // 'editorBracketPairGuide.activeBackground1': '',
        // 'editorBracketPairGuide.activeBackground2': '',
        // 'editorBracketPairGuide.activeBackground3': '',
        // 'editorBracketPairGuide.activeBackground4': '',
        // 'editorBracketPairGuide.activeBackground5': '',
        // 'editorBracketPairGuide.activeBackground6': '',
        // 'editorBracketPairGuide.background1': '',
        // 'editorBracketPairGuide.background2': '',
        // 'editorBracketPairGuide.background3': '',
        // 'editorBracketPairGuide.background4': '',
        // 'editorBracketPairGuide.background5': '',
        // 'editorBracketPairGuide.background6': '',
        'editor.foldBackground': lightness(palette.bg, 8),
        'editorOverviewRuler.background': palette.bg,
        'editorOverviewRuler.border': palette.bg,
        // 'editorOverviewRuler.findMatchForeground': '',
        // 'editorOverviewRuler.rangeHighlightForeground': '',
        // 'editorOverviewRuler.selectionHighlightForeground': '',
        // 'editorOverviewRuler.wordHighlightForeground': '',
        // 'editorOverviewRuler.wordHighlightStrongForeground': '',
        // 'editorOverviewRuler.modifiedForeground': '',
        'editorOverviewRuler.addedForeground': palette.green,
        'editorOverviewRuler.deletedForeground': alpha(palette.red, .6),
        'editorOverviewRuler.errorForeground': palette.red,
        'editorOverviewRuler.warningForeground': palette.yellow,
        // 'editorOverviewRuler.infoForeground': '',
        // 'editorOverviewRuler.bracketMatchForeground': '',
        'editorError.foreground': alpha(palette.red, .6),
        // 'editorError.border': palette.red,
        // 'editorError.background': alpha(palette.red, 1),
        'editorWarning.foreground': palette.yellow,
        //   'editorWarning.border': null,
        //   'editorWarning.background': null,
        'editorInfo.foreground': palette.blue,
        //   'editorInfo.border': palette.blue,
        //   'editorInfo.background': '',
        'editorHint.foreground': palette.blue,
        //   'editorHint.border': palette.red,
        // 'problemsErrorIcon.foreground': '',
        // 'problemsWarningIcon.foreground': '',
        // 'problemsInfoIcon.foreground': '',
        'editorUnnecessaryCode.border': alpha(lightness(palette.bg, 16), .2),
        'editorUnnecessaryCode.opacity': '#00000099',

        'editorGutter.background': palette.bg,
        'editorGutter.modifiedBackground': palette.yellow,
        'editorGutter.addedBackground': palette.green,
        'editorGutter.deletedBackground': palette.red,
        // 'editorGutter.commentRangeForeground': '',
        'editorGutter.foldingControlForeground': lightness(palette.fg, -32),

        // 'editorCommentsWidget.resolvedBorder': '',
        // 'editorCommentsWidget.unresolvedBorder': '',
        // 'editorCommentsWidget.rangeBackground': '',
        // 'editorCommentsWidget.rangeBorder': '',
        // 'editorCommentsWidget.rangeActiveBackground': '',
        // 'editorCommentsWidget.rangeActiveBorder': '',
    }
}