exports.symbolIcons = function(color) {
    return {
        'symbolIcon.arrayForeground': color.fgMuted,
        'symbolIcon.booleanForeground': color.fgMuted,
        'symbolIcon.classForeground': color.fgMuted,
        'symbolIcon.colorForeground': color.fgMuted,
        'symbolIcon.constantForeground': color.fgMuted,
        'symbolIcon.constructorForeground': color.fgMuted,
        'symbolIcon.enumeratorForeground': color.fgMuted,
        'symbolIcon.enumeratorMemberForeground': color.fgMuted,
        'symbolIcon.eventForeground': color.fgMuted,
        'symbolIcon.fieldForeground': color.fgMuted,
        'symbolIcon.fileForeground': color.fgMuted,
        'symbolIcon.folderForeground': color.fgMuted,
        'symbolIcon.functionForeground': color.fgMuted,
        'symbolIcon.interfaceForeground': color.fgMuted,
        'symbolIcon.keyForeground': color.fgMuted,
        'symbolIcon.keywordForeground': color.fgMuted,
        'symbolIcon.methodForeground': color.fgMuted,
        'symbolIcon.moduleForeground': color.fgMuted,
        'symbolIcon.namespaceForeground': color.fgMuted,
        'symbolIcon.nullForeground': color.fgMuted,
        'symbolIcon.numberForeground': color.fgMuted,
        'symbolIcon.objectForeground': color.fgMuted,
        'symbolIcon.operatorForeground': color.fgMuted,
        'symbolIcon.packageForeground': color.fgMuted,
        'symbolIcon.propertyForeground': color.fgMuted,
        'symbolIcon.referenceForeground': color.fgMuted,
        'symbolIcon.snippetForeground': color.fgMuted,
        'symbolIcon.stringForeground': color.fgMuted,
        'symbolIcon.structForeground': color.fgMuted,
        'symbolIcon.textForeground': color.fgMuted,
        'symbolIcon.typeParameterForeground': color.fgMuted,
        'symbolIcon.unitForeground': color.fgMuted,
        'symbolIcon.variableForeground': color.fgMuted
    }
}