exports.symbolIcons = function(palette) {
    return {
        'symbolIcon.arrayForeground': palette.fgMuted,
        'symbolIcon.booleanForeground': palette.fgMuted,
        'symbolIcon.classForeground': palette.fgMuted,
        'symbolIcon.colorForeground': palette.fgMuted,
        'symbolIcon.constantForeground': palette.fgMuted,
        'symbolIcon.constructorForeground': palette.fgMuted,
        'symbolIcon.enumeratorForeground': palette.fgMuted,
        'symbolIcon.enumeratorMemberForeground': palette.fgMuted,
        'symbolIcon.eventForeground': palette.fgMuted,
        'symbolIcon.fieldForeground': palette.fgMuted,
        'symbolIcon.fileForeground': palette.fgMuted,
        'symbolIcon.folderForeground': palette.fgMuted,
        'symbolIcon.functionForeground': palette.fgMuted,
        'symbolIcon.interfaceForeground': palette.fgMuted,
        'symbolIcon.keyForeground': palette.fgMuted,
        'symbolIcon.keywordForeground': palette.fgMuted,
        'symbolIcon.methodForeground': palette.fgMuted,
        'symbolIcon.moduleForeground': palette.fgMuted,
        'symbolIcon.namespaceForeground': palette.fgMuted,
        'symbolIcon.nullForeground': palette.fgMuted,
        'symbolIcon.numberForeground': palette.fgMuted,
        'symbolIcon.objectForeground': palette.fgMuted,
        'symbolIcon.operatorForeground': palette.fgMuted,
        'symbolIcon.packageForeground': palette.fgMuted,
        'symbolIcon.propertyForeground': palette.fgMuted,
        'symbolIcon.referenceForeground': palette.fgMuted,
        'symbolIcon.snippetForeground': palette.fgMuted,
        'symbolIcon.stringForeground': palette.fgMuted,
        'symbolIcon.structForeground': palette.fgMuted,
        'symbolIcon.textForeground': palette.fgMuted,
        'symbolIcon.typeParameterForeground': palette.fgMuted,
        'symbolIcon.unitForeground': palette.fgMuted,
        'symbolIcon.variableForeground': palette.fgMuted
    }
}