exports.symbolIcons = function(color) {
    return {
        'symbolIcon.arrayForeground': color.fgDimmed,
        'symbolIcon.booleanForeground': color.fgDimmed,
        'symbolIcon.classForeground': color.fgDimmed,
        'symbolIcon.colorForeground': color.fgDimmed,
        'symbolIcon.constantForeground': color.fgDimmed,
        'symbolIcon.constructorForeground': color.fgDimmed,
        'symbolIcon.enumeratorForeground': color.fgDimmed,
        'symbolIcon.enumeratorMemberForeground': color.fgDimmed,
        'symbolIcon.eventForeground': color.fgDimmed,
        'symbolIcon.fieldForeground': color.fgDimmed,
        'symbolIcon.fileForeground': color.fgDimmed,
        'symbolIcon.folderForeground': color.fgDimmed,
        'symbolIcon.functionForeground': color.fgDimmed,
        'symbolIcon.interfaceForeground': color.fgDimmed,
        'symbolIcon.keyForeground': color.fgDimmed,
        'symbolIcon.keywordForeground': color.fgDimmed,
        'symbolIcon.methodForeground': color.fgDimmed,
        'symbolIcon.moduleForeground': color.fgDimmed,
        'symbolIcon.namespaceForeground': color.fgDimmed,
        'symbolIcon.nullForeground': color.fgDimmed,
        'symbolIcon.numberForeground': color.fgDimmed,
        'symbolIcon.objectForeground': color.fgDimmed,
        'symbolIcon.operatorForeground': color.fgDimmed,
        'symbolIcon.packageForeground': color.fgDimmed,
        'symbolIcon.propertyForeground': color.fgDimmed,
        'symbolIcon.referenceForeground': color.fgDimmed,
        'symbolIcon.snippetForeground': color.fgDimmed,
        'symbolIcon.stringForeground': color.fgDimmed,
        'symbolIcon.structForeground': color.fgDimmed,
        'symbolIcon.textForeground': color.fgDimmed,
        'symbolIcon.typeParameterForeground': color.fgDimmed,
        'symbolIcon.unitForeground': color.fgDimmed,
        'symbolIcon.variableForeground': color.fgDimmed
    }
}