const { lightness, saturation } = require('../base/util');

exports.terminal = function(color) {
    return {
        'terminal.background': color.bg,
        'terminal.border': color.bg,
        'terminal.foreground': color.fgBright,
        'terminal.ansiBlack': lightness(color.bg, 32),
        'terminal.ansiBrightBlack': lightness(color.bg, 64),
        'terminal.ansiBrightBlue': saturation(color.blue, 10),
        'terminal.ansiBrightCyan': saturation(color.cyan, 10),
        'terminal.ansiBrightGreen': saturation(color.green, 10),
        'terminal.ansiBrightMagenta': saturation(color.magenta, 10),
        'terminal.ansiBrightRed': saturation(color.red, 10),
        'terminal.ansiBrightYellow': saturation(color.yellow, 10),
        'terminal.ansiBrightWhite': color.fgBright,
        'terminal.ansiBlue': color.blue,
        'terminal.ansiCyan': color.cyan,
        'terminal.ansiGreen': color.green,
        'terminal.ansiMagenta': color.magenta,
        'terminal.ansiRed': color.red,
        'terminal.ansiWhite': color.fg,
        'terminal.ansiYellow': color.yellow,
        'terminal.selectionBackground': lightness(color.bg, 6),
        // 'terminal.selectionForeground': null,
        'terminal.findMatchBackground': lightness(color.bg, 4),
        // 'terminal.findMatchBorder': '',
        'terminal.findMatchHighlightBackground': lightness(color.bg, 4),
        // 'terminal.findMatchHighlightBorder': '',
        'terminalCursor.background': color.fg,
        'terminalCursor.foreground': color.fg,
        // 'terminal.dropBackground': '',
        'terminal.tab.activeBorder': color.cyan,
        // 'terminalCommandDecoration.defaultBackground': '',
        // 'terminalCommandDecoration.successBackground': '',
        // 'terminalCommandDecoration.errorBackground': '',
        // 'terminalOverviewRuler.cursorForeground': '',
        // 'terminalOverviewRuler.findMatchForeground': ''
    }
}